import * as XLSX from 'xlsx'
import { PeriodSnapshot } from '@/lib/report-snapshot'
import { toCsv, csvDate, csvMoney, CsvValue } from '@/lib/csv-export'

/**
 * The data-shaped exports of a period snapshot.
 *
 * The workbook is the honest home for "everything": relational data needs more
 * than one table, and a sheet per entity keeps the relationships intact.
 * The CSV is a single flat table by definition, so it carries the one join
 * people actually work with — a row per order line, with the customer and
 * order columns denormalised alongside it.
 */

const STATUS_LABEL: Record<string, string> = {
  pending_approval: 'Pending approval',
  processing: 'Processing',
  out_for_delivery: 'Out for delivery',
  delivered: 'Delivered',
  invoice_ready: 'Send invoice',
  invoice_blocked: 'Invoice blocked',
  paid: 'Paid',
}

const label = (s: string) => STATUS_LABEL[s] ?? s

// ── Sheet definitions ───────────────────────────────────────────────────────
// Each returns [headers, ...rows] so the same shape feeds both XLSX and CSV.

function summarySheet(snap: PeriodSnapshot): CsvValue[][] {
  const k = snap.kpis
  return [
    ['SPika CRM — period report'],
    [],
    ['Period', snap.meta.label],
    ['From', snap.meta.from],
    ['To', snap.meta.to],
    ['Generated at', snap.meta.generatedAt],
    ['Generated by', snap.meta.generatedBy],
    ['Counting rule', 'Sales are counted on their invoice date, which is the delivery date'],
    [],
    ['Revenue (XCG)', k.revenue],
    ['Of which consignment', k.revenueConsignment],
    ['Of which cash', k.revenueCash],
    ['Still open, not in revenue', k.revenueOpen],
    ['Average order', k.averageOrder],
    [],
    ['Bottles sold', k.bottles],
    ['Real volume (L)', k.realVolumeMl / 1000],
    ['Orders total', k.ordersTotal],
    ['Orders delivered', k.ordersDelivered],
    ['Orders still open', k.ordersOpen],
    [],
    ['Customers active', k.customersActive],
    ['Customers that ordered', k.customersOrdering],
    ['New customers', k.customersNew],
    ['New leads', k.leadsNew],
    [],
    ['Reconciliation — sum of orders', snap.reconciliation.revenueFromOrders],
    ['Reconciliation — sum of customer rows', snap.reconciliation.revenueFromCustomerRows],
    ['Reconciliation — difference', snap.reconciliation.difference],
    ['Reconciliation — ties', snap.reconciliation.ties ? 'YES' : 'NO'],
  ]
}

function customersSheet(snap: PeriodSnapshot): CsvValue[][] {
  const head = [
    'Customer no.', 'Company', 'Category', 'Status', 'Consignment', 'Contact', 'E-mail', 'Phone', 'WhatsApp',
    'Delivery city', 'Billing city', 'Country', 'Payment term (days)', 'VAT', 'CoC', 'CRIB',
    'Customer since', 'Orders in period', 'Revenue in period', 'Bottles in period', 'Internal notes',
  ]
  const rows = snap.customers.map(c => [
    c.customer_number ?? '', c.company_name, c.customer_category, c.status, c.is_consignment ? 'yes' : 'no',
    c.contact_person, c.email, c.phone, c.whatsapp,
    c.delivery_city, c.billing_city, c.billing_country, c.payment_term_days, c.vat_number, c.coc_number, c.crib_number,
    csvDate(c.created_at), c.orderCount, csvMoney(c.revenue), c.bottles, c.internal_notes,
  ])
  return [head, ...rows]
}

function ordersSheet(snap: PeriodSnapshot): CsvValue[][] {
  const head = [
    'Order no.', 'PO no.', 'Customer', 'Category', 'Status', 'Invoice date (= delivery date)', 'Planned date',
    'Created', 'Paid date', 'Payment type', 'Consignment', 'Order type', 'Currency', 'Total',
    'Delivered at', 'Signed by', 'Delivery notes',
  ]
  const rows = snap.orders.map(o => [
    o.order_number, o.po_number ?? '', o.customer_name, o.customer_category, label(o.status),
    o.sales_date, o.planned_date ?? '', csvDate(o.created_at), o.paid_date ?? '',
    o.payment_type, o.is_consignment ? 'yes' : 'no', o.order_type, o.currency, csvMoney(o.total),
    o.delivered_at ? csvDate(o.delivered_at) : '', o.signer_name ?? '', o.delivery_notes,
  ])
  return [head, ...rows]
}

/** A row per order line — the flat table the CSV export is built on. */
function orderLinesRows(snap: PeriodSnapshot): CsvValue[][] {
  const head = [
    'Order no.', 'Invoice date', 'Status', 'Customer no.', 'Customer', 'Category', 'City',
    'SKU', 'Product', 'Qty', 'Unit price', 'Discount', 'Line total', 'Currency',
    'Consignment', 'Payment type', 'Order total', 'Delivered at', 'Signed by',
  ]
  const byId = new Map(snap.customers.map(c => [c.id, c]))
  const rows: CsvValue[][] = []
  for (const o of snap.orders) {
    const c = byId.get(o.customer_id)
    const items = (o.items ?? []).filter(i => Number(i.qty) > 0)
    if (items.length === 0) {
      rows.push([
        o.order_number, o.sales_date, label(o.status), c?.customer_number ?? '', o.customer_name, o.customer_category,
        c?.delivery_city ?? '', '', '(no line items)', 0, '', '', '', o.currency,
        o.is_consignment ? 'yes' : 'no', o.payment_type, csvMoney(o.total),
        o.delivered_at ? csvDate(o.delivered_at) : '', o.signer_name ?? '',
      ])
      continue
    }
    for (const i of items) {
      rows.push([
        o.order_number, o.sales_date, label(o.status), c?.customer_number ?? '', o.customer_name, o.customer_category,
        c?.delivery_city ?? '', i.sku, i.name ?? i.sku, i.qty, csvMoney(i.unit_price), csvMoney(i.discount),
        csvMoney(i.line_total), o.currency,
        o.is_consignment ? 'yes' : 'no', o.payment_type, csvMoney(o.total),
        o.delivered_at ? csvDate(o.delivered_at) : '', o.signer_name ?? '',
      ])
    }
  }
  return [head, ...rows]
}

function productsSheet(snap: PeriodSnapshot): CsvValue[][] {
  return [
    ['SKU', 'Product', 'Qty', 'Revenue', 'Real volume (L)'],
    ...snap.byProduct.map(p => [
      p.sku, p.name, p.qty, csvMoney(p.revenue), p.volumeMl != null ? (p.volumeMl / 1000).toFixed(2) : '',
    ]),
  ]
}

function outstandingSheet(snap: PeriodSnapshot): CsvValue[][] {
  return [
    ['Order no.', 'Customer', 'Invoice date', 'Due date', 'Days overdue', 'Amount'],
    ...snap.outstanding.map(o => [
      o.order.order_number, o.order.customer_name, o.order.sales_date, o.dueDate,
      o.daysOverdue > 0 ? o.daysOverdue : 0, csvMoney(o.order.total),
    ]),
  ]
}

function leadsSheet(snap: PeriodSnapshot): CsvValue[][] {
  return [
    ['Company', 'Category', 'Contact', 'E-mail', 'Phone', 'Added', 'Touchpoints in period'],
    ...snap.leads.map(l => [
      l.company_name, l.customer_category, l.contact_person, l.email, l.phone,
      csvDate(l.created_at), l.contactMoments.length,
    ]),
  ]
}

function contactSheet(snap: PeriodSnapshot): CsvValue[][] {
  const rows: CsvValue[][] = []
  for (const c of [...snap.customers, ...snap.leads]) {
    for (const t of c.contactMoments) {
      rows.push([c.company_name, c.is_lead ? 'lead' : 'customer', t.date, t.channel, t.by, t.note])
    }
  }
  rows.sort((a, b) => String(a[2]).localeCompare(String(b[2])))
  return [['Company', 'Type', 'Date', 'Channel', 'Spoke to', 'Note'], ...rows]
}

// ── Public builders ─────────────────────────────────────────────────────────

/** Multi-sheet workbook — the "everything" export. */
export function buildWorkbook(snap: PeriodSnapshot): Buffer {
  const wb = XLSX.utils.book_new()
  const add = (name: string, rows: CsvValue[][]) => {
    const ws = XLSX.utils.aoa_to_sheet(rows)
    // Give every column a workable width instead of the 8-character default.
    const widths = (rows[0] ?? []).map((_, i) => ({
      wch: Math.min(48, Math.max(10, ...rows.slice(0, 200).map(r => String(r[i] ?? '').length + 2))),
    }))
    ws['!cols'] = widths
    XLSX.utils.book_append_sheet(wb, ws, name)
  }

  add('Summary', summarySheet(snap))
  add('Customers', customersSheet(snap))
  add('Orders', ordersSheet(snap))
  add('Order lines', orderLinesRows(snap))
  add('Products', productsSheet(snap))
  add('Outstanding', outstandingSheet(snap))
  add('Leads', leadsSheet(snap))
  add('Contact log', contactSheet(snap))

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer
}

/** Flat CSV: one row per order line. BOM so Excel reads the accents. */
export function buildCsv(snap: PeriodSnapshot): string {
  const rows = orderLinesRows(snap)
  return '﻿' + toCsv(rows[0].map(String), rows.slice(1))
}
